-- Albion Discord Bot — initial schema.
--
-- Conventions:
--   Discord snowflakes  -> BIGINT (they exceed 32-bit)
--   Albion entity ids   -> VARCHAR(64) (base64-ish strings, e.g. "wqtbQ6teS5OxIs9ObZrCUA")
--   Silver amounts      -> BIGINT (integral by nature; never floating point)
--   Timestamps          -> TIMESTAMPTZ
--
-- Tenancy: config / balance / registration are per-Discord-server. The `battle`
-- and `battle_participation` tables are global game-world data — one battle is one
-- row regardless of how many Discord servers care about it. Tenancy is applied at
-- query time by joining through `registration`.


-- ---------------------------------------------------------------------------
-- Per-Discord-server configuration, written by /setup
-- ---------------------------------------------------------------------------
CREATE TABLE discord_guild_config (
    discord_guild_id      BIGINT       PRIMARY KEY,
    staff_role_id         BIGINT,
    verified_role_id      BIGINT,
    log_channel_id        BIGINT,
    killboard_channel_id  BIGINT,
    cta_min_players       INT          NOT NULL DEFAULT 30,
    setup_completed       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0
);


-- ---------------------------------------------------------------------------
-- Which in-game guilds count as "ours" (/guild add)
-- ---------------------------------------------------------------------------
CREATE TABLE tracked_albion_guild (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_guild_id         BIGINT       NOT NULL
        REFERENCES discord_guild_config (discord_guild_id) ON DELETE CASCADE,
    albion_guild_id          VARCHAR(64)  NOT NULL,
    albion_guild_name        VARCHAR(128) NOT NULL,
    alliance_id              VARCHAR(64),
    alliance_tag             VARCHAR(32),
    added_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    added_by_discord_user_id BIGINT,
    CONSTRAINT ux_tracked_guild UNIQUE (discord_guild_id, albion_guild_id)
);

-- The battle poller filters every incoming battle against this column.
CREATE INDEX ix_tracked_guild_albion ON tracked_albion_guild (albion_guild_id);


-- ---------------------------------------------------------------------------
-- Registrations: Discord user <-> Albion character
-- ---------------------------------------------------------------------------
CREATE TABLE registration (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_guild_id         BIGINT       NOT NULL
        REFERENCES discord_guild_config (discord_guild_id) ON DELETE CASCADE,
    discord_user_id          BIGINT       NOT NULL,
    albion_player_id         VARCHAR(64)  NOT NULL,
    albion_player_name       VARCHAR(64)  NOT NULL,
    albion_player_name_lower VARCHAR(64)  NOT NULL,

    registered_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- false when force-registered: guild membership was never confirmed
    verified                 BOOLEAN      NOT NULL DEFAULT TRUE,
    force_registered_by      BIGINT,

    -- Soft delete, so the audit trail and re-registration history survive.
    active                   BOOLEAN      NOT NULL DEFAULT TRUE,
    unregistered_at          TIMESTAMPTZ,
    unregistered_by          BIGINT,

    last_validated_at        TIMESTAMPTZ,
    last_validation_ok       BOOLEAN,

    -- Fame baseline captured at registration. This is what makes the
    -- "since joining" deltas in /stats possible; false when a force-register
    -- could not reach the API, in which case /stats says so rather than lying.
    snapshot_available       BOOLEAN      NOT NULL DEFAULT FALSE,
    snapshot_taken_at        TIMESTAMPTZ,
    snapshot_kill_fame       BIGINT,
    snapshot_death_fame      BIGINT,
    snapshot_pve_fame        BIGINT,
    snapshot_gathering_fame  BIGINT,
    snapshot_crafting_fame   BIGINT,
    snapshot_fishing_fame    BIGINT,
    snapshot_farming_fame    BIGINT
);

-- Partial unique indexes: only ACTIVE registrations are constrained, so a user
-- can re-register after being unregistered. Hibernate cannot generate these,
-- which is one of the reasons this project uses Flyway rather than ddl-auto.
CREATE UNIQUE INDEX ux_registration_user
    ON registration (discord_guild_id, discord_user_id) WHERE active;

-- Blocks two Discord users claiming the same character — the impersonation
-- case that /unregister exists for.
CREATE UNIQUE INDEX ux_registration_player
    ON registration (discord_guild_id, albion_player_id) WHERE active;

CREATE INDEX ix_registration_active ON registration (discord_guild_id) WHERE active;
CREATE INDEX ix_registration_player_id ON registration (albion_player_id);


-- ---------------------------------------------------------------------------
-- Balances
-- ---------------------------------------------------------------------------
-- Deliberately no optimistic-lock version column: every write is a single
-- atomic statement (see BalanceDao), so row locks in the database provide the
-- serialisation and application-level retry logic is unnecessary.
CREATE TABLE balance (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_guild_id BIGINT      NOT NULL
        REFERENCES discord_guild_config (discord_guild_id) ON DELETE CASCADE,
    discord_user_id  BIGINT      NOT NULL,
    amount           BIGINT      NOT NULL DEFAULT 0,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_balance UNIQUE (discord_guild_id, discord_user_id)
);


-- ---------------------------------------------------------------------------
-- Append-only ledger. Every balance mutation writes one row here in the same
-- transaction as the mutation itself.
-- ---------------------------------------------------------------------------
CREATE TABLE balance_transaction (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_guild_id              BIGINT      NOT NULL,
    discord_user_id               BIGINT      NOT NULL,
    actor_discord_user_id         BIGINT,
    -- ADD | REMOVE | RESET | GIVE_OUT | GIVE_IN | PAYOUT
    type                          VARCHAR(24) NOT NULL,
    delta                         BIGINT      NOT NULL,
    balance_after                 BIGINT      NOT NULL,
    counterparty_discord_user_id  BIGINT,
    -- payout batch id / role id, so one /payout can be reconstructed later
    reference                     VARCHAR(64),
    note                          VARCHAR(512),
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_balance_tx_user
    ON balance_transaction (discord_guild_id, discord_user_id, created_at DESC);
CREATE INDEX ix_balance_tx_reference ON balance_transaction (reference);


-- ---------------------------------------------------------------------------
-- Battles (global game data)
-- ---------------------------------------------------------------------------
-- The Albion battle id is the primary key, and that IS the idempotency
-- guarantee: re-ingesting a battle is an ON CONFLICT no-op.
CREATE TABLE battle (
    albion_battle_id BIGINT      PRIMARY KEY,
    start_time       TIMESTAMPTZ NOT NULL,
    end_time         TIMESTAMPTZ,
    total_fame       BIGINT      NOT NULL DEFAULT 0,
    total_kills      INT         NOT NULL DEFAULT 0,
    -- size of the battle's `players` map; the CTA test compares against this
    player_count     INT         NOT NULL DEFAULT 0,
    guild_count      INT         NOT NULL DEFAULT 0,
    alliance_count   INT         NOT NULL DEFAULT 0,
    ingested_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_battle_start_time ON battle (start_time);
CREATE INDEX ix_battle_player_count ON battle (player_count);


CREATE TABLE battle_participation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    albion_battle_id    BIGINT       NOT NULL
        REFERENCES battle (albion_battle_id) ON DELETE CASCADE,
    albion_player_id    VARCHAR(64)  NOT NULL,
    -- name and guild AS AT the battle; both change over time
    albion_player_name  VARCHAR(64)  NOT NULL,
    albion_guild_id     VARCHAR(64),
    albion_guild_name   VARCHAR(128),
    kills               INT          NOT NULL DEFAULT 0,
    deaths              INT          NOT NULL DEFAULT 0,
    kill_fame           BIGINT       NOT NULL DEFAULT 0,
    -- Denormalised from `battle` so /stats is one indexed scan instead of a
    -- join plus aggregate. Immutable once written. battle_player_count must be
    -- here specifically because the CTA threshold is per-server configurable
    -- and therefore has to be applied at query time.
    battle_start_time   TIMESTAMPTZ  NOT NULL,
    battle_player_count INT          NOT NULL,
    CONSTRAINT ux_battle_participation UNIQUE (albion_battle_id, albion_player_id)
);

CREATE INDEX ix_participation_player
    ON battle_participation (albion_player_id, battle_start_time);


-- ---------------------------------------------------------------------------
-- Killboard posts. Keyed per Discord server rather than stored on `battle`,
-- because `battle` is global: two Discord servers tracking guilds in the same
-- fight must each get their own post, and each needs its own message id.
-- ---------------------------------------------------------------------------
CREATE TABLE killboard_post (
    discord_guild_id BIGINT      NOT NULL
        REFERENCES discord_guild_config (discord_guild_id) ON DELETE CASCADE,
    albion_battle_id BIGINT      NOT NULL
        REFERENCES battle (albion_battle_id) ON DELETE CASCADE,
    message_id       BIGINT,
    posted_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (discord_guild_id, albion_battle_id)
);


-- ---------------------------------------------------------------------------
-- Periodic fame snapshots, used for the "since joining" deltas in /stats
-- ---------------------------------------------------------------------------
CREATE TABLE player_fame_snapshot (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    albion_player_id VARCHAR(64) NOT NULL,
    captured_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    kill_fame        BIGINT      NOT NULL DEFAULT 0,
    death_fame       BIGINT      NOT NULL DEFAULT 0,
    pve_fame         BIGINT      NOT NULL DEFAULT 0,
    gathering_fame   BIGINT      NOT NULL DEFAULT 0,
    crafting_fame    BIGINT      NOT NULL DEFAULT 0,
    fishing_fame     BIGINT      NOT NULL DEFAULT 0,
    farming_fame     BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX ix_fame_snapshot_player
    ON player_fame_snapshot (albion_player_id, captured_at DESC);


-- ---------------------------------------------------------------------------
-- Poller watermark / health
-- ---------------------------------------------------------------------------
CREATE TABLE poller_state (
    id                   VARCHAR(64) PRIMARY KEY,
    last_run_at          TIMESTAMPTZ,
    last_success_at      TIMESTAMPTZ,
    consecutive_failures INT         NOT NULL DEFAULT 0,
    -- /stats reports the true data window honestly using this
    first_ingest_at      TIMESTAMPTZ
);

INSERT INTO poller_state (id) VALUES ('battles');
