-- Objectives: "this pops at 20:00 UTC", shared in the channel (/objective add|show).
--
-- Stored as an absolute instant, not the HH:MM that was typed. Both of the things
-- /objective show does need a date before they are answerable at all:
--
--   * Ordering closest-first across midnight. At 23:55 UTC, 00:10 is fifteen minutes
--     away and 23:50 is five minutes past — but compared as bare times 00:10 sorts
--     first and reads as the one furthest off.
--   * Expiry. An objective drops off once the clock is past it by the grace window, and
--     today's 20:00 half an hour ago is indistinguishable from tomorrow's 20:00 unless
--     the row knows which day it means.
--
-- HH:MM is resolved on the way in, to the next occurrence of that time at or after the
-- moment it was added, so an objective always sits inside the coming 24 hours.
CREATE TABLE objective (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_guild_id         BIGINT       NOT NULL
        REFERENCES discord_guild_config (discord_guild_id) ON DELETE CASCADE,
    name                     VARCHAR(100) NOT NULL,
    -- When it pops. The HH:MM UTC that was typed is this, rendered back.
    pops_at                  TIMESTAMPTZ  NOT NULL,
    added_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    added_by_discord_user_id BIGINT
);

-- /objective show reads one server's list in pop order, and deletes what has expired
-- by the same key. Both are this index.
CREATE INDEX ix_objective_guild_pops ON objective (discord_guild_id, pops_at);

-- Two people relaying the same intel must not put it on the list twice. Case-insensitive,
-- because "Fort Sterling" and "fort sterling" are one objective. The same name at another
-- time is not a duplicate: a chest pops more than once a day.
CREATE UNIQUE INDEX ux_objective_name_time ON objective (discord_guild_id, lower(name), pops_at);
